# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cprl < Formula
  desc "Multipurpose command line tool for AWS to make development life easier"
  homepage "https://github.com/JamesChung/cprl"
  version "0.0.0-prealpha-20230403043234"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/JamesChung/cprl/releases/download/v0.0.0-prealpha-20230403043234/cprl_Darwin_arm64.tar.gz"
      sha256 "b94bfdf0e5b618dfd214c52aace473d2c057df1c564b7836d46850b433cd5ba8"

      def install
        bin.install "cprl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/JamesChung/cprl/releases/download/v0.0.0-prealpha-20230403043234/cprl_Darwin_x86_64.tar.gz"
      sha256 "1d8f3221cb7fb387ae4ded5c51b626d75561b2bf96b6c282c491e8c629252576"

      def install
        bin.install "cprl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JamesChung/cprl/releases/download/v0.0.0-prealpha-20230403043234/cprl_Linux_arm64.tar.gz"
      sha256 "0c81661bf631ccf7e3de49bb8eb2d72eb88516c1656993ed78228d914ff42f0f"

      def install
        bin.install "cprl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/JamesChung/cprl/releases/download/v0.0.0-prealpha-20230403043234/cprl_Linux_x86_64.tar.gz"
      sha256 "4f02a3b15fba5b0eea64186f11801e5b6f7f24c329af0d32a04c12e39f24a205"

      def install
        bin.install "cprl"
      end
    end
  end
end
